openscad -D "part=\""barrel\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-pins.stl barrel-hinge.scad

openscad -D "part=\""barrel\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-large-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-large-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""bambu\""" -o ../../stl/barrel-hinge/bambu/bambu_barrel-hinge-large-pins.stl barrel-hinge.scad

openscad -D "part=\""barrel\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-pins.stl barrel-hinge.scad

openscad -D "part=\""barrel\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-large-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-large-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""mingda\""" -o ../../stl/barrel-hinge/mingda/mingda_barrel-hinge-large-pins.stl barrel-hinge.scad

openscad -D "part=\""barrel\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=24;height=20;hole_d=3;number_of_arms=4;arm_thickness=2;arm_width=3;arm_hole_wall=1.2;extra_margin_front=2;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-pins.stl barrel-hinge.scad

openscad -D "part=\""barrel\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-large-barrel.stl barrel-hinge.scad
openscad -D "part=\""arm\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-large-arm.stl barrel-hinge.scad
openscad -D "part=\""pins\"";barrel_d=55;height=45;hole_d=8;number_of_arms=6;arm_thickness=4;arm_width=6;arm_hole_wall=3;extra_margin_front=3;extra_arm_length=0;printer=\""default\""" -o ../../stl/barrel-hinge/barrel-hinge-large-pins.stl barrel-hinge.scad
